language: php

services:
  - memcached

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-add travis.php.ini; fi;'
  - composer self-update
  - composer install --no-interaction --prefer-source
